### ISSUE TITLE
Batch Delete with predicate including Contains on empty list generates invalid SQL

### ISSUE THREAD

**Issue by Jawvig** [zzzprojects/EntityFramework.Extended#94]
(Using version NuGet version 6.1.0.93 on EF 6.1.0)
The following code throws a SqlException (contained within an AggregateException) with the message "Invalid column name 'ID'."

```
            using (var context = new MyContext())
            {
                context.Contacts.Add(new Contact());
                context.SaveChanges();

                var contactIds = new List<int>(); //context.Contacts.Select(c => c.ID).ToList();
                context.Contacts.Delete(c => contactIds.Contains(c.ID));
                context.SaveChanges();
            }
```

The exception is thrown on the call to `.Delete` and not `.SaveChanges`.

Executing the same code with values inside the list (i.e. replacing the `new List<int>` with the commented out portion of that line) works as expected.

The full stack trace is:

```
(for the inner SqlException:)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at EntityFramework.Batch.SqlServerBatchRunner.<InternalDelete>d__0`1.MoveNext()

(for the AggregateException:)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at EntityFramework.Batch.SqlServerBatchRunner.Delete[TEntity](ObjectContext objectContext, EntityMap entityMap, ObjectQuery`1 query)
   at EntityFramework.Extensions.BatchExtensions.Delete[TEntity](IQueryable`1 source)
   at EntityFramework.Extensions.BatchExtensions.Delete[TEntity](IQueryable`1 source, Expression`1 filterExpression)
   at ConsoleApplication3.Program.Main(String[] args) in c:\Users\Joshua\Documents\Visual Studio 2013\Projects\ConsoleApplication3\Program.cs:line 20
```

**Comment by nguyen190887** [comment]
+1

I faced the same issue when using Batch Update, but I thought the reason should be same.
My code is (invalidatedAssetIDs is an empty 'integer' list):
```
_assetRepository.BulkUpdate(
                x => invalidatedAssetIDs.Contains(x.AssetID),
                x => new Asset() { Status = AssetStatus.NotFound });
```

and the generated script got from SQL Profiler is:
```
exec sp_executesql N'UPDATE [dbo].[tblAsset] SET 
[Status] = @p__update__0 
FROM [dbo].[tblAsset] AS j0 INNER JOIN (
SELECT 
    1 AS [C1], 
    CAST(NULL AS int) AS [C2]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
    WHERE 1 = 0
) AS j1 ON (j0.[AssetID] = j1.[AssetID])',N'@p__update__0 smallint',@p__update__0=4
```

Note that, BulkUpdate is a wrapping method defined as below
```
public virtual int BulkUpdate(Expression<Func<T, bool>> filterExpression, Expression<Func<T, T>> updateExpression)
{
	return _context.Set<T>().Where(filterExpression).Update(updateExpression);
}
```

**Comment by decease** [comment]
+1

**Comment by zbend** [comment]
+1

**Comment by oguzhantopcu** [comment]
+1

**Comment by Hugibeer** [comment]
+1

**Comment by JonathanMagnan** [comment]
Hello @Hugibeer and everyone else,

This library is no longer supported since 2015 and has been replaced by [Entity Framework Plus](http://entityframework-plus.net/) which is also free.

You can try our library and create a request [here](https://github.com/zzzprojects/EntityFramework-Plus) if we also do not support it.

Best Regards,

Jonathan
